version: '2'
services:
    academy-app:
        image: academy
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://academy-postgresql:5432/academy
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    academy-postgresql:
        extends:
            file: postgresql.yml
            service: academy-postgresql
