version: '2'
services:
    academy-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/academy/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=academy
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
